### ISSUE TITLE
Méta-ticket pour les différents scénarios de métadonnées

### ISSUE THREAD

**Issue by RochDLY** [EcrituresNumeriques/stylo#1021]
On regroupe tous les scénarios de métadonnées dans ce ticket

- [x] Chapitre de thèse et mémoire #1024 
- [x] Article de revue #1019
- [x] Chapitre de livre #1023 
- [x] Note de réunion #1025 
- [x] Billet de blog #1026
- [ ] Vide

**Comment by gromettoclara** [comment]
Proposition: récup de certaines md dans un article que l'utilisateur choisit et intégrer dans le corpus thèse ou mémoire
Pour homogénéiser
